### ISSUE TITLE
Disable field when readonly is set to true in the blueprint

### ISSUE THREAD

**Issue by SamuelRiversMoore** [lukaskleinschmidt/kirby-sortable#35]
Hello, thank you very much for this plugin : it is exactly what I was looking for.

It seems that it is not yet possible to disable the field via blueprint or permissions. 

Not sure if it's the best option but here's a css solution : 

```
.field-is-readonly .sortable a,
.field-is-readonly .sortable .sortable-layout [data-handle],
.field-is-readonly .sortable .sortable-layout__action{
  cursor: default;
  pointer-events: none;
}
.field-is-readonly .sortable .sortable-layout {
  background: #efefef;
  border-color: #ddd;
  color: #777;
}
.field-is-readonly .sortable .sortable-layout__icon {
  border-left-color: #ccc;
  background: #efefef;
}
.field-is-readonly .sortable .sortable-layout__action {
  color: #c9c9c9;
}
```

**Comment by lukaskleinschmidt** [comment]
The readonly thingy is a tricky one. I put a lot of thought into it and decided to left it open.

The main reason is that the field does not really output any content. It saves the order to the page but it is actually mostly needed internally (there are edge cases). The problem is to define waht should be editable and what should not.
In some use cases sorting the pages and not being able to edit or delete a page would be the right choice. In other cases it could be the complete opposite or both.

I think the css solution is the right choice here. I will probably add something to the readme.

You can use permissions to enable / disable actions (eg. edit, duplicate, delete, toggle).
