### ISSUE TITLE
Add page title for new entries

### ISSUE THREAD

**Issue by movingwater** [lukaskleinschmidt/kirby-sortable#42]
I use the sortable field for displaying blogpost entries, so no modules plugin is used...
Is there a way to add the page title field, when adding new entries, like the build in way on adding new pages. Then you would already have readable page urls and you don't have to change them afterwards.
I remember that is was discussed at some places, but I couldn't find where.

Thanks for all your effort and this awesome plugin.

**Comment by lukaskleinschmidt** [comment]
Yes that is possible. Please have a closer look at the [customize ](https://github.com/lukaskleinschmidt/kirby-sortable#action) section. You need a customized `add` action. 

I actually put something together because it is easier to understand I think :wink:.
https://github.com/lukaskleinschmidt/kirby-sortable-action-add

You can basically modify almost every aspect of the field.
